
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_CHAVES ABRE_PAREN ALERTA BOOL DESLIGAR DIFERENTE DISPOSITIVO DOIS_PONTOS ELOGICO ENTAO ENVIAR FECHA_CHAVES FECHA_PAREN ID IGUAL IGUAL_SIMPLES LIGAR MAIOR MAIORIGUAL MENOR MENORIGUAL NUM PARA PONTO SE SENAO SET STRING TODOS VIRGULAprogram : devices cmdsdevices : device devicesdevices : devicedevice : DISPOSITIVO DOIS_PONTOS ABRE_CHAVES ID VIRGULA ID FECHA_CHAVESdevice : DISPOSITIVO DOIS_PONTOS ABRE_CHAVES ID FECHA_CHAVEScmds : cmd PONTO cmdscmds : cmd PONTOcmd : SET ID IGUAL_SIMPLES valorcmd : LIGAR IDcmd : DESLIGAR IDcmd : ENVIAR ALERTA ABRE_PAREN STRING FECHA_PAREN IDcmd : ENVIAR ALERTA ABRE_PAREN STRING VIRGULA ID FECHA_PAREN IDcmd : SE condicao ENTAO cmdcmd : SE condicao ENTAO cmd SENAO cmdcmd : ENVIAR ALERTA ABRE_PAREN STRING FECHA_PAREN PARA TODOS DOIS_PONTOS namedevice_listnamedevice_list : ID VIRGULA namedevice_listnamedevice_list : IDcondicao : ID operador valorcondicao : ID operador valor ELOGICO condicaooperador : MAIOR\n| MENOR\n| MAIORIGUAL\n| MENORIGUAL\n| IGUAL\n| DIFERENTEvalor : NUM\n| ID'
    
_lr_action_items = {'DISPOSITIVO':([0,3,41,52,],[4,4,-5,-4,]),'$end':([1,5,14,22,],[0,-1,-7,-6,]),'SET':([2,3,12,14,25,41,44,52,],[7,-3,-2,7,7,-5,7,-4,]),'LIGAR':([2,3,12,14,25,41,44,52,],[8,-3,-2,8,8,-5,8,-4,]),'DESLIGAR':([2,3,12,14,25,41,44,52,],[9,-3,-2,9,9,-5,9,-4,]),'ENVIAR':([2,3,12,14,25,41,44,52,],[10,-3,-2,10,10,-5,10,-4,]),'SE':([2,3,12,14,25,41,44,52,],[11,-3,-2,11,11,-5,11,-4,]),'DOIS_PONTOS':([4,53,],[13,55,]),'PONTO':([6,16,17,34,35,36,38,47,50,56,57,58,60,],[14,-9,-10,-27,-8,-26,-13,-11,-14,-12,-15,-17,-16,]),'ID':([7,8,9,11,21,23,26,27,28,29,30,31,32,40,42,43,45,54,55,59,],[15,16,17,20,33,34,34,-20,-21,-22,-23,-24,-25,46,47,49,20,56,58,58,]),'ALERTA':([10,],[18,]),'ABRE_CHAVES':([13,],[21,]),'IGUAL_SIMPLES':([15,],[23,]),'SENAO':([16,17,34,35,36,38,47,50,56,57,58,60,],[-9,-10,-27,-8,-26,44,-11,-14,-12,-15,-17,-16,]),'ABRE_PAREN':([18,],[24,]),'ENTAO':([19,34,36,39,51,],[25,-27,-26,-18,-19,]),'MAIOR':([20,],[27,]),'MENOR':([20,],[28,]),'MAIORIGUAL':([20,],[29,]),'MENORIGUAL':([20,],[30,]),'IGUAL':([20,],[31,]),'DIFERENTE':([20,],[32,]),'NUM':([23,26,27,28,29,30,31,32,],[36,36,-20,-21,-22,-23,-24,-25,]),'STRING':([24,],[37,]),'VIRGULA':([33,37,58,],[40,43,59,]),'FECHA_CHAVES':([33,46,],[41,52,]),'ELOGICO':([34,36,39,],[-27,-26,45,]),'FECHA_PAREN':([37,49,],[42,54,]),'PARA':([42,],[48,]),'TODOS':([48,],[53,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'devices':([0,3,],[2,12,]),'device':([0,3,],[3,3,]),'cmds':([2,14,],[5,22,]),'cmd':([2,14,25,44,],[6,6,38,50,]),'condicao':([11,45,],[19,51,]),'operador':([20,],[26,]),'valor':([23,26,],[35,39,]),'namedevice_list':([55,59,],[57,60,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> devices cmds','program',2,'p_program','parser.py',35),
  ('devices -> device devices','devices',2,'p_devices_multiple','parser.py',41),
  ('devices -> device','devices',1,'p_devices_single','parser.py',45),
  ('device -> DISPOSITIVO DOIS_PONTOS ABRE_CHAVES ID VIRGULA ID FECHA_CHAVES','device',7,'p_device_obs','parser.py',49),
  ('device -> DISPOSITIVO DOIS_PONTOS ABRE_CHAVES ID FECHA_CHAVES','device',5,'p_device_simple','parser.py',55),
  ('cmds -> cmd PONTO cmds','cmds',3,'p_cmds_multiple','parser.py',60),
  ('cmds -> cmd PONTO','cmds',2,'p_cmds_single','parser.py',64),
  ('cmd -> SET ID IGUAL_SIMPLES valor','cmd',4,'p_cmd_set','parser.py',68),
  ('cmd -> LIGAR ID','cmd',2,'p_cmd_ligar','parser.py',78),
  ('cmd -> DESLIGAR ID','cmd',2,'p_cmd_desligar','parser.py',82),
  ('cmd -> ENVIAR ALERTA ABRE_PAREN STRING FECHA_PAREN ID','cmd',6,'p_cmd_alerta_simples','parser.py',86),
  ('cmd -> ENVIAR ALERTA ABRE_PAREN STRING VIRGULA ID FECHA_PAREN ID','cmd',8,'p_cmd_alerta_obs','parser.py',90),
  ('cmd -> SE condicao ENTAO cmd','cmd',4,'p_cmd_if','parser.py',101),
  ('cmd -> SE condicao ENTAO cmd SENAO cmd','cmd',6,'p_cmd_if_else','parser.py',105),
  ('cmd -> ENVIAR ALERTA ABRE_PAREN STRING FECHA_PAREN PARA TODOS DOIS_PONTOS namedevice_list','cmd',9,'p_cmd_alerta_broadcast','parser.py',109),
  ('namedevice_list -> ID VIRGULA namedevice_list','namedevice_list',3,'p_namedevice_list_multiple','parser.py',118),
  ('namedevice_list -> ID','namedevice_list',1,'p_namedevice_list_single','parser.py',122),
  ('condicao -> ID operador valor','condicao',3,'p_condicao_simples','parser.py',126),
  ('condicao -> ID operador valor ELOGICO condicao','condicao',5,'p_condicao_dupla','parser.py',130),
  ('operador -> MAIOR','operador',1,'p_operador','parser.py',134),
  ('operador -> MENOR','operador',1,'p_operador','parser.py',135),
  ('operador -> MAIORIGUAL','operador',1,'p_operador','parser.py',136),
  ('operador -> MENORIGUAL','operador',1,'p_operador','parser.py',137),
  ('operador -> IGUAL','operador',1,'p_operador','parser.py',138),
  ('operador -> DIFERENTE','operador',1,'p_operador','parser.py',139),
  ('valor -> NUM','valor',1,'p_valor','parser.py',143),
  ('valor -> ID','valor',1,'p_valor','parser.py',144),
]
